# -*- coding: utf-8 -*-
"""eyesproject8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdQeXmewXhU9wwjlODKxS12AVwReif8f
"""
import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.set_page_config(page_title="Eye Gender Classification", page_icon="👁", layout="wide")

st.markdown("""
<style>
.main{background-color:#f5f7fa;}
.title{text-align:center;color:#0d47a1;font-size:45px;font-weight:bold;}
.subtitle{text-align:center;color:gray;font-size:18px;}
.footer{text-align:center;color:gray;font-size:14px;}
</style>
""", unsafe_allow_html=True)

@st.cache_resource
def load_model():
    try:
        return tf.keras.models.load_model("my_model.keras")
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.stop()

model = load_model()
IMG_SIZE = (299, 299)

st.markdown("<div class='title'>👁 Eye Gender Classification using CNN</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Deep Learning Based Eye Gender Prediction</div>", unsafe_allow_html=True)

c1,c2=st.columns(2)
with c1:
    st.info("""### 👩 Student Details

**Name:** Aditi Srivastava

**Roll No:** 2401221550005

**Course:** B.Tech CSE (IoT)
""")
with c2:
    st.success("""### 🏫 College

Shri Ramswaroop Memorial College of Engineering & Management

Framework: TensorFlow

Deployment: Streamlit

Model: CNN
""")

st.divider()
st.markdown("## 📖 About Project")
st.write("""
This project predicts whether an uploaded eye image belongs to a **Male** or **Female** using a CNN.

- Image Upload
- Eye Image Preview
- Gender Prediction
- Confidence Score
- Interactive Dashboard
""")

st.divider()
st.markdown("## 📤 Upload Eye Image")

uploaded_file = st.file_uploader("Choose an Eye Image", type=["jpg","jpeg","png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns(2)

    with col1:
        st.image(image, caption="Uploaded Eye Image", use_container_width=True)

    img = image.resize(IMG_SIZE)
    img = np.array(img).astype("float32")/255.0
    img = np.expand_dims(img, axis=0)

    with st.spinner("Predicting..."):
        prediction = model.predict(img, verbose=0)

    probability = float(prediction[0][0])

    if probability >= 0.5:
        predicted_class = "Male"
        confidence = probability * 100
    else:
        predicted_class = "Female"
        confidence = (1-probability) * 100

    with col2:
        st.markdown("## 🤖 Prediction")
        if predicted_class == "Male":
            st.success(f"### Prediction: {predicted_class}")
        else:
            st.info(f"### Prediction: {predicted_class}")

        st.metric("Confidence", f"{confidence:.2f}%")
        st.progress(min(int(confidence),100))

        st.markdown("### 📊 Prediction Probability")
        st.write(f"**Male:** {probability*100:.2f}%")
        st.write(f"**Female:** {(1-probability)*100:.2f}%")
else:
    st.info("👆 Please upload an eye image to get a prediction.")

st.sidebar.title("📌 Model Information")
st.sidebar.success("""
**Algorithm**: CNN

**Framework**: TensorFlow/Keras

**Input Size**: 299×299

**Formats**: JPG, JPEG, PNG
""")
st.sidebar.info("This project predicts gender from an eye image using a CNN.")

st.divider()
st.markdown("""
<div class='footer'>
Developed by <b>Aditi Srivastava</b><br>
B.Tech CSE (IoT)<br>
Roll No. 2401221550005<br>
Shri Ramswaroop Memorial College of Engineering & Management
</div>
""", unsafe_allow_html=True)
